### ISSUE TITLE
(ERROR) tailscale-dev/docker-mod:main digest could not be fetched from ghcr.io

### ISSUE THREAD

**Issue by gauravsuman007** [tailscale-dev/docker-mod#19]
I'm trying to add tailscale mod to the qbittorrent container using docker compose as follows:

```
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8089
      # Enable tailscale mod
      - DOCKER_MODS=ghcr.io/tailscale-dev/docker-mod:main
```

However, when starting the container, I get the following error:
```
qbittorrent  | [mod-init] Running Docker Modification Logic
qbittorrent  | [mod-init] Adding tailscale-dev/docker-mod:main to container
qbittorrent  | [mod-init] (ERROR) tailscale-dev/docker-mod:main digest could not be fetched from ghcr.io
```

Am I missing something? I have double checked the mod address but it seems to be fine. Is the ghcr.io image down?
