### ISSUE TITLE
not working with filezilla container

### ISSUE THREAD

**Issue by allthecogs** [tailscale-dev/docker-mod#25]
I am using the linuxserver.io filezilla container, which launches ok and has the GUI, however, when I add the tailscale mod to it, it no longer works.
In a console for the container I have run "tailscale up --accept-routes", then authenticated and approved it in my tailscale dashboard.

If I run "tailscale ip -4" I get a tailscale IP address (which matches my ts dashboard), however I get page not displayed error trying to access the container web UI using either the IP address on the tailnet (and the port) or the host IP and port (which is how I accessed it before the mod).
When I go to the container console and run "filezilla -v", I get the following error:

> Reading locale option from /config/.config/filezilla/filezilla.xml
> 11:44:09: Error: Unable to initialize GTK+, is DISPLAY set properly?`

If I then run "echo $DISPLAY", I get an output of 1, which is what it should be, but nothing is being displayed.

On a non-tailscale mod container, doing the same I get:

> Reading locale option from /config/.config/filezilla/filezilla.xml
> FileZilla 3.67.0, compiled on 2024-05-15

This is my docker compose file:

```
services:
  filezilla:
    image: lscr.io/linuxserver/filezilla:latest
    container_name: filezilla
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Berlin
      - DOCKER_MODS=ghcr.io/tailscale-dev/docker-mod:main
      # tailscale information
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
      - TAILSCALE_SERVE_PORT=80
      - TAILSCALE_SERVE_MODE=https
      ## uncomment to enable funnel, may be a bad idea for some use cases
      #- TAILSCALE_FUNNEL=on
      - TAILSCALE_USE_SSH=1
      - TAILSCALE_HOSTNAME=filezllatailscale
      - TAILSCALE_AUTHKEY=tskey-auth-mygerneratedauthkey

    volumes:
      - /volume2/docker/filezilla:/config
      - /volume2/data:/data:rw
    ports:
      - 3010:3000
      - 3011:3001
    restart: unless-stopped
```

docker logs:

[filezilla_docker_logs.txt](https://github.com/user-attachments/files/16690308/filezilla_docker_logs.txt)

A bit of background on my use case, as I'm sure someone will ask. My main storage is at site A, where this docker container is running (on a Synology NAS). I want to transfer selected files to Site B, which is an archive of critical data. As it is selected files, I do not want to use rsync or syncthing etc, as it is not an entire directory that is replicated. I prefer the manual approach.
Site B is plagued by power cuts, so connectivity constantly goes during transfer. I have been using filezilla in a windows VM with desktop tailscale installed, but that uses a lot of resources, hence going the docker approach with a web UI. I like filezilla for SFTP transfers, since I can resume after a connection loss, but I need it to be part of my tailnet
