### ISSUE TITLE
Docker mod connection always uses relay

### ISSUE THREAD

**Issue by rdmchr** [tailscale-dev/docker-mod#3]
I have tailscale installed on the server itself and one container using the docker mod (the container is on the same server). When I connect to the server itself and use `tailscale status` I see the following output:
```
100.64.209.68   node-one             marc@        linux   active; direct [:::::2]:41641
```
But when I connect to the docker container I get this output:
```
100.117.194.108 jellyfin             tagged-devices linux   active; relay "mia"
```
As you can see I'm trying to run Jellyfin, which doesn't work correctly over the slow relay connection. Here is my docker-compose.yml
```yaml
services:
  jellyfin:
    image: linuxserver/jellyfin:10.8.9
    container_name: jellyfin
    hostname: jellyfin
    networks:
      - traefik-network
    volumes:
      - data:/config
      - tailscale:/var/lib/tailscale
    restart: unless-stopped
    environment:
      - PUID=911
      - PGID=1001
      - TZ=Etc/UTC
      - DOCKER_MODS=ghcr.io/tailscale-dev/docker-mod:main
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
      - TAILSCALE_SERVE_MODE=https
      - TAILSCALE_SERVE_PORT=80
      - TAILSCALE_USE_SSH=0
      - TAILSCALE_HOSTNAME=jellyfin
      - TAILSCALE_AUTHKEY=
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(``)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=le"
      - "traefik.http.routers.jellyfin.middlewares=authentik-proxy@docker"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=80"

networks:
  traefik-network:
    external: true
    name: traefik

volumes:
  data:
    external: true
    name: jellyfin_data
  tailscale:
```
Is the traefik network interfering with the Tailscale connection? If so, is there any work around that would still allow me to use traefik?

**Comment by wbste** [comment]
Ever figure this out? None of my containers use direct unless I'm on lan.

**Comment by wirgakatz** [comment]
I recently had a similar problem with using the tailscale docker mod in a swag container. 
After troubleshooting the problem with a separate standalone container, I observed that the tailscale connection would be direct when using the bridge network. If I selected the custom Docker network, Tailscale would only establish connections via a relay.
So in the end, my solution was to give the swag container first access to the bridge network and also add the custom docker network.
After doing this, i have direct connections to my services while still being able to use the custom docker network for swag and these services.
I verified that the connection is indeed direct using the tailscale ping command and just general speedtests which would show a clear increase in bandwidth.

**Comment by wbste** [comment]
> I recently had a similar problem with using the tailscale docker mod in a swag container. After troubleshooting the problem with a separate standalone container, I observed that the tailscale connection would be direct when using the bridge network. If I selected the custom Docker network, Tailscale would only establish connections via a relay. So in the end, my solution was to give the swag container first access to the bridge network and also add the custom docker network. After doing this, i have direct connections to my services while still being able to use the custom docker network for swag and these services. I verified that the connection is indeed direct using the tailscale ping command and just general speedtests which would show a clear increase in bandwidth.

But a [bridge network](https://docs.docker.com/engine/network/drivers/bridge/) is always created, right?

I tried this but never got direct access either. Maybe it's a Windows/WSL2 thing?

```
services:
  tailscale:
    image: tailscale/tailscale:latest
    hostname: tailscale
    environment:
      - TS_AUTHKEY=tskey-...
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    networks:
      - default  # bridge network
      - custom_network  # custom network
   
  nginx:
    image: nginx
    depends_on:
      - tailscale
    network_mode: service:tailscale

networks:
  custom_network:
    driver: bridge
```
